export { default as HeroSection } from './Hero'
export { default as CTASection } from './CTASection'
export { default as SectionOne } from './SectionOne'
export { default as KeyBenefitsSction } from './KeyBenefits'
export { default as SecurityFeaturesSection } from './SecurityFeaturesSection'
